services:
  - type: web
    name: vitrine-katalog
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: COOKIE_SECURE
        value: "true"
      - key: DB_DIR
        value: /var/data
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
